spring.datasource.url=jdbc:postgresql://localhost:5432/dpi_db
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update

# ? TURN OFF SQL LOGGING
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ? DISABLE HIBERNATE LOG SPAM
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=OFF

# ? Keep logs readable
logging.level.org.springframework=INFO